"""empty message

Revision ID: 81a3b2a6d11d
Revises: 6d89f72d58c4
Create Date: 2018-12-12 13:29:14.051316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a3b2a6d11d'
down_revision = '6d89f72d58c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(length=5), nullable=False, server_default='en_US'))
    op.add_column('users', sa.Column('phone', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'language')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
